#!/usr/bin/env node
// design-md skill: render a spec.json into DESIGN.md + preview.html.
//
// Usage: node preview.mjs <spec.json> --out <dir> [--md-only]
//
// Emits:
//   <dir>/DESIGN.md         design-system doc for coding agents (9 sections)
//   <dir>/preview.html      human-verifiable visual catalog (light)
//   <dir>/preview-dark.html (dark)

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

async function main() {
  const argv = process.argv.slice(2);
  const specPath = argv.find((a) => !a.startsWith("--"));
  const outIdx = argv.indexOf("--out");
  const outDir = outIdx >= 0 ? argv[outIdx + 1] : ".";
  if (!specPath) { console.error("Usage: node preview.mjs <spec.json> --out <dir>"); process.exit(1); }
  const spec = JSON.parse(await readFile(specPath, "utf8"));
  await mkdir(outDir, { recursive: true });

  await writeFile(join(outDir, "DESIGN.md"), renderDesignMd(spec));
  if (!argv.includes("--md-only")) {
    await writeFile(join(outDir, "preview.html"), renderPreview(spec, false));
    await writeFile(join(outDir, "preview-dark.html"), renderPreview(spec, true));
  }
  console.log(`wrote ${join(outDir, "DESIGN.md")}${argv.includes("--md-only") ? "" : `, preview.html, preview-dark.html`}`);
}

// ------------------------------- DESIGN.md --------------------------------

function rows(items, cols) {
  return (items ?? []).map((it) => cols.map((c) => it[c] ?? "—").join(" | ")).join("\n");
}

function renderDesignMd(spec) {
  const t = spec.typography ?? {};
  const colors = spec.colors ?? [];
  const button = spec.components?.button ?? {};
  const card = spec.components?.card ?? {};
  const input = spec.components?.input ?? {};
  const nav = spec.components?.navItem ?? {};
  const layout = spec.layout ?? {};
  const depth = spec.depth ?? [];
  const theme = spec.theme ?? {};
  const responsive = spec.responsive ?? {};
  const rules = spec.rules ?? {};
  const guide = spec.promptGuide ?? {};

  return `# ${spec.sourceDomain ?? "Untitled"} — DESIGN.md

> Auto-generated by the design-md skill${spec.generatedBy ? ` · ${spec.generatedBy}` : ""}.
> Source: ${spec.sourceUrl} · Captured: ${(spec.capturedAt ?? "—").slice(0, 10)}

## Visual Theme & Atmosphere

${theme.atmosphere ?? "—"}

Density: **${theme.density ?? "standard"}**

## Color Palette & Roles

| Role | Value | Usage |
|------|-------|-------|
${rows(colors, ["role", "hex", "description"])}

## Typography Rules

Font families: sans \`${t.fontFamilies?.sans ?? "system"}\`${t.fontFamilies?.serif ? `, serif \`${t.fontFamilies.serif}\`` : ""}${t.fontFamilies?.mono ? `, mono \`${t.fontFamilies.mono}\`` : ""}

| Style | Size | Weight | Line height | Tracking | Font |
|-------|------|--------|-------------|----------|------|
${rows(t.typeScale ?? [], ["name", "size", "weight", "lineHeight", "letterSpacing", "font"])}

## Component Stylings

### Buttons

Radius: ${button.borderRadius ?? "—"} · Padding: ${button.padding ?? "—"} · Weight: ${button.fontWeight ?? "—"}

| Variant | Background | Text | Border | Hover |
|---------|-----------|------|--------|-------|
${rows(button.variants ?? [], ["variant", "background", "text", "border", "hover"])}

### Cards

Background: ${card.background ?? "—"} · Border: ${card.border ?? "none"} · Radius: ${card.borderRadius ?? "—"} · Shadow: ${card.shadow ?? "none"}

### Inputs

Background: ${input.background ?? "—"} · Border: ${input.border ?? "—"} · Radius: ${input.borderRadius ?? "—"} · Focus: ${input.focusBorder ?? "—"} · Padding: ${input.padding ?? "—"}

### Navigation

Inactive: ${nav.inactive ?? "—"} · Active: ${nav.active ?? "—"} · Active bg: ${nav.activeBackground ?? "transparent"} · Radius: ${nav.borderRadius ?? "—"}

## Layout Principles

Spacing scale: ${(layout.spacingScale ?? []).join(", ") || "—"}

Grid: ${layout.gridColumns ?? "—"} columns · Max width: ${layout.containerMaxWidth ?? "—"} · Content padding: ${layout.contentPadding ?? "—"} · Section gap: ${layout.sectionGap ?? "—"}

## Depth & Elevation

| Level | Shadow | Use |
|-------|--------|-----|
${rows(depth, ["name", "shadow", "description"])}

## Do's and Don'ts

**Do:**
${(rules.do ?? []).map((d) => `- ${d}`).join("\n") || "- _none specified_"}

**Don't:**
${(rules.dont ?? []).map((d) => `- ${d}`).join("\n") || "- _none specified_"}

## Responsive Behavior

| Breakpoint | Width | Layout |
|------------|-------|--------|
${rows(responsive.breakpoints ?? [], ["name", "width", "layout"])}

Touch targets: ${responsive.touchTargets ?? "—"}

Collapse strategy: ${responsive.collapseStrategy ?? "—"}

## Agent Prompt Guide

Quick reference: \`${guide.quickReference ?? "—"}\`

Starter prompts:

${(guide.starterPrompts ?? []).map((p) => `- "${p}"`).join("\n") || "- _none specified_"}
`;
}

// ------------------------------- preview.html ------------------------------

function renderPreview(spec, dark) {
  const t = spec.typography ?? {};
  const colors = spec.colors ?? [];
  const button = spec.components?.button ?? {};
  const card = spec.components?.card ?? {};
  const nav = spec.components?.navItem ?? {};
  const darkMode = spec.theme?.darkMode ?? {};

  const hex = (role) => {
    if (!role) return "";
    if (role.startsWith("#")) return role;
    return colors.find((c) => c.role === role)?.hex ?? "";
  };
  const color = (role) => {
    if (!role || role === "none" || role === "transparent") return "transparent";
    if (role.startsWith("#")) return role;
    if (dark) {
      const dm = {
        background: darkMode.background,
        "background-elevated": darkMode.surface,
        "background-inverse": darkMode.background,
        "text-primary": darkMode.text,
        "text-secondary": darkMode.textSecondary,
        "text-on-dark": darkMode.text,
        border: darkMode.border
      };
      if (dm[role]) return dm[role];
    }
    return hex(role) || "transparent";
  };
  const swatchHex = (role) => (dark && color(role) !== "transparent" && color(role) !== hex(role) ? color(role) : hex(role));
  const typoSample = (font) => (font === "serif" ? `Georgia, 'Times New Roman', serif` : font === "mono" ? `ui-monospace, 'Cascadia Code', Consolas, monospace` : `ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif`);

  const buttonVariants = (button.variants ?? []).map((v) => {
    const bg = color(v.background);
    const fg = color(v.text);
    const border = v.border && v.border !== "none" ? `1px solid ${color(v.border)}` : "none";
    const hover = color(v.hover);
    return `<button style="background:${bg};color:${fg};border:${border};border-radius:${button.borderRadius ?? "6px"};padding:${button.padding ?? "10px 24px"};font-weight:${button.fontWeight ?? 600};cursor:pointer" onmouseover="this.style.background='${hover}'" onmouseout="this.style.background='${bg}'">${v.variant}</button>`;
  }).join("\n        ");

  const navItems = ["Home", "Products", "Pricing", "Docs", "About"].map((label, i) => {
    const active = i === 0;
    return `<a style="background:${active ? color(nav.activeBackground) : "transparent"};color:${active ? color(nav.active) : color(nav.inactive)};border-radius:${nav.borderRadius ?? "6px"};padding:6px 12px;text-decoration:none;font-weight:${active ? 600 : 400}">${label}</a>`;
  }).join("\n        ");

  const depthCards = (spec.depth ?? []).map((d) => `
        <div class="depth-card" style="box-shadow:${d.shadow};background:${color("background-elevated")};border:1px solid ${color("border")};border-radius:${card.borderRadius ?? "12px"};padding:20px"><strong>${d.name}</strong><br><span style="color:${color("text-secondary")}">${d.description}</span></div>`).join("\n");

  const breakpoints = (spec.responsive?.breakpoints ?? []).map((b) => `<div class="depth-card" style="background:${color("background-elevated")};border:1px solid ${color("border")};border-radius:${card.borderRadius ?? "12px"};padding:16px"><strong>${b.name}</strong> <span style="color:${color("text-secondary")}">≥${b.width}px</span><br><span style="color:${color("text-secondary")};font-size:0.9em">${b.layout}</span></div>`).join("\n          ");

  return `<!doctype html>
<html lang="en" data-theme="${dark ? "dark" : "light"}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${spec.sourceDomain ?? "Site"} — DESIGN.md preview${dark ? " (dark)" : ""}</title>
<style>
  :root {
    --bg: ${dark ? darkMode.background ?? "#111" : hex("background") || "#fff"};
    --surface: ${dark ? darkMode.surface ?? "#1a1a1a" : hex("background-elevated") || "#fff"};
    --text: ${dark ? darkMode.text ?? "#f5f5f5" : hex("text-primary") || "#111"};
    --text-2: ${dark ? darkMode.textSecondary ?? "#aaa" : hex("text-secondary") || "#666"};
    --border: ${dark ? darkMode.border ?? "#333" : hex("border") || "#e5e5e5"};
  }
  * { box-sizing: border-box; margin: 0; }
  body { background: var(--bg); color: var(--text); font-family: ${typoSample(t.fontFamilies?.sans)}; padding: 40px 24px 80px; }
  .wrap { max-width: 960px; margin: 0 auto; }
  header { display: flex; align-items: baseline; justify-content: space-between; gap: 16px; margin-bottom: 40px; }
  header h1 { font-size: 1.5rem; font-weight: 700; }
  header a { color: var(--text-2); font-size: 0.9rem; }
  section { margin-top: 48px; }
  h2 { font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.08em; color: var(--text-2); margin-bottom: 16px; }
  .swatches { display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); gap: 12px; }
  .swatch { border: 1px solid var(--border); border-radius: 12px; overflow: hidden; background: var(--surface); }
  .swatch .chip { height: 64px; }
  .swatch .meta { padding: 10px 12px; }
  .swatch .role { font-weight: 600; font-size: 0.85rem; }
  .swatch .value { font-size: 0.8rem; color: var(--text-2); }
  .buttons { display: flex; gap: 12px; flex-wrap: wrap; }
  .type-row { display: flex; gap: 24px; align-items: baseline; border-bottom: 1px solid var(--border); padding: 14px 0; }
  .type-row .spec { min-width: 180px; color: var(--text-2); font-size: 0.85rem; }
  .nav-demo { display: flex; gap: 4px; margin-top: 8px; }
  .nav-demo a { padding: 6px 12px; border-radius: 6px; text-decoration: none; }
  .depth-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 12px; }
  .card-demo { background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: 20px; }
  .card-demo h3 { margin-bottom: 6px; }
  .card-demo p { color: var(--text-2); font-size: 0.9rem; line-height: 1.5; }
  .card-demo .row { display: flex; gap: 8px; margin-top: 16px; }
  .footer { margin-top: 64px; color: var(--text-2); font-size: 0.85rem; border-top: 1px solid var(--border); padding-top: 24px; }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>${spec.sourceDomain ?? "Site"}</h1>
    <a>${dark ? "dark" : "light"} preview · source: ${spec.sourceUrl}</a>
  </header>

  <section>
    <h2>Colors</h2>
    <div class="swatches">
${colors.map((c) => `      <div class="swatch"><div class="chip" style="background:${swatchHex(c.role)}"></div><div class="meta"><div class="role">${c.role}</div><div class="value">${dark && swatchHex(c.role) !== c.hex ? `${swatchHex(c.role)} <span style="opacity:.6">(light: ${c.hex})</span>` : c.hex}</div></div></div>`).join("\n")}
    </div>
  </section>

  <section>
    <h2>Typography</h2>
${(t.typeScale ?? []).map((s) => `    <div class="type-row"><div class="spec">${s.name} · ${s.size} · ${s.weight}</div><div style="font-size:${s.size};font-weight:${s.weight};line-height:${s.lineHeight};letter-spacing:${s.letterSpacing ?? "normal"};font-family:${typoSample(s.font)}">The quick brown fox jumps over the lazy dog</div></div>`).join("\n")}
  </section>

  <section>
    <h2>Buttons</h2>
    <div class="buttons">
        ${buttonVariants}
    </div>
  </section>

  <section>
    <h2>Navigation</h2>
    <div class="nav-demo">
        ${navItems}
    </div>
  </section>

  <section>
    <h2>Cards</h2>
    <div class="card-demo">
      <h3>Sample card</h3>
      <p>${spec.theme?.atmosphere ?? ""}</p>
      <div class="row">
        <button style="background:${color(button.variants?.[0]?.background)};color:${color(button.variants?.[0]?.text)};border:none;border-radius:${button.borderRadius ?? "6px"};padding:${button.padding ?? "10px 24px"};font-weight:600;cursor:pointer">Primary action</button>
        <button style="background:transparent;color:${color("text-primary")};border:1px solid ${color("border")};border-radius:${button.borderRadius ?? "6px"};padding:${button.padding ?? "10px 24px"};font-weight:600;cursor:pointer">Secondary</button>
      </div>
    </div>
  </section>

  <section>
    <h2>Depth & Elevation</h2>
    <div class="depth-grid">${depthCards}
    </div>
  </section>

  <section>
    <h2>Responsive breakpoints</h2>
    <div class="depth-grid">${breakpoints}
    </div>
  </section>

  <div class="footer">
    Generated by <strong>design-md</strong> skill · ${spec.generatedBy ?? ""} · captured ${(spec.capturedAt ?? "").slice(0, 10)} · Do's: ${(spec.rules?.do ?? []).length} · Don'ts: ${(spec.rules?.dont ?? []).length}
  </div>
</div>
</body>
</html>`;
}

main().catch((e) => { console.error("preview failed:", e.message); process.exit(1); });
